default:
  input_profile:
    input_synid: syn26340641
    project_id: syn25791888
    network_method: ["genie3"]
    na_fill: NULL
    p_val_c3net: 1
    p_val_mrnet: 1
    p_val_wgcna: 1
    temp_storage_loc: /home/sage
    rsquaredCut: 0.80
    defaultnaPower: 6
  provenance:
    annotations:
      data_type: ['clinical','geneExpression']
      resource_type: metadata
      metadata_type: 'analytical covariates'
      ismodelsystem: FALSE
      ismultispecimen: TRUE
      fileformat: csv
      grant: U01AG046152
      species: Human
      organ: brain
      tissue: ['dorsolateral prefrontal cortex', 'Head of caudate nucleus', 'posterior cingulate cortex']
      study: ["ROSMAP","rnaSeqReprocessing"]
      consortium: AMP-AD
      assay: rnaSeq
    code_annotations:
        repository: PradoVarathan/Reprocessing_Metanetwork_Analysis
        ref: branch
        ref_name: main
        repository_path: Network_Wrapper.R
    activity_name: genie3_rosmap_network
    activity_description: 'Using the genie3 to prepare network from rosmap data'
  output_profile:
    output_path: genie3
    md5_output_path: genie3_md5.out
    output_name: 'Final Rosmap Network from genie3'
    error_path: genie3_err
  computing_specs:
    light_ncores: 96
    medium_ncores: 128
    heavy_ncores: 256
